// Generated by hand from the project's Supabase schema (see GENERICK_DATABASE_FIXED.xlsx).
// If the schema changes, regenerate with the Supabase CLI instead of hand-editing:
//   npx supabase gen types typescript --project-id <ref> > src/types/database.ts

export type ProfileRole = "user" | "clinic_staff" | "admin";
export type PatientType = "student" | "faculty" | "staff";
export type Sex = "male" | "female";
export type KioskStatus = "active" | "inactive";
export type RiskLevel = "low" | "moderate" | "high";

export interface Database {
	public: {
		Views: Record<string, never>;
		Functions: Record<string, never>;
		Tables: {
			profiles: {
				Row: {
					profile_id: string;
					auth_id: string | null;
					role: ProfileRole;
					first_name: string;
					last_name: string;
					email: string;
					created_at: string;
				};
				Insert: {
					profile_id?: string;
					auth_id?: string | null;
					role: ProfileRole;
					first_name: string;
					last_name: string;
					email: string;
					created_at?: string;
				};
				Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
			
				Relationships: [];
			};
			patients: {
				Row: {
					patient_id: string;
					profile_id: string;
					patient_type: PatientType;
					identification_number: string | null;
					course: string | null;
					department: string | null;
					sex: Sex | null;
					birthdate: string | null;
					contact_number: string | null;
					address_legacy: string | null;
					country: string | null;
					region: string | null;
					province: string | null;
					city_municipality: string | null;
					barangay: string | null;
					street: string | null;
					house_number: string | null;
					created_at: string;
				};
				Insert: {
					patient_id?: string;
					profile_id: string;
					patient_type: PatientType;
					identification_number?: string | null;
					course?: string | null;
					department?: string | null;
					sex?: Sex | null;
					birthdate?: string | null;
					contact_number?: string | null;
					address_legacy?: string | null;
					country?: string | null;
					region?: string | null;
					province?: string | null;
					city_municipality?: string | null;
					barangay?: string | null;
					street?: string | null;
					house_number?: string | null;
					created_at?: string;
				};
				Update: Partial<Database["public"]["Tables"]["patients"]["Insert"]>;
			
				Relationships: [
					{
						foreignKeyName: "fk_profile";
						columns: ["profile_id"];
						isOneToOne: true;
						referencedRelation: "profiles";
						referencedColumns: ["profile_id"];
					}
				];
			};
			kiosks: {
				Row: {
					kiosk_id: string;
					kiosk_name: string;
					location: string | null;
					serial_number: string | null;
					status: KioskStatus;
					created_at: string;
				};
				Insert: {
					kiosk_id?: string;
					kiosk_name: string;
					location?: string | null;
					serial_number?: string | null;
					status?: KioskStatus;
					created_at?: string;
				};
				Update: Partial<Database["public"]["Tables"]["kiosks"]["Insert"]>;
			
				Relationships: [];
			};
			health_records: {
				Row: {
					record_id: string;
					patient_id: string;
					kiosk_id: string | null;
					measured_by: string | null;
					systolic: number | null;
					diastolic: number | null;
					heart_rate: number | null;
					temperature: number | null;
					spo2: number | null;
					height: number | null;
					weight: number | null;
					bmi: number | null;
					measured_at: string;
				};
				Insert: {
					record_id?: string;
					patient_id: string;
					kiosk_id?: string | null;
					measured_by?: string | null;
					systolic?: number | null;
					diastolic?: number | null;
					heart_rate?: number | null;
					temperature?: number | null;
					spo2?: number | null;
					height?: number | null;
					weight?: number | null;
					bmi?: number | null;
					measured_at?: string;
				};
				Update: Partial<Database["public"]["Tables"]["health_records"]["Insert"]>;
			
				Relationships: [
					{
						foreignKeyName: "health_records_patient_id_fkey";
						columns: ["patient_id"];
						isOneToOne: false;
						referencedRelation: "patients";
						referencedColumns: ["patient_id"];
					},
					{
						foreignKeyName: "health_records_kiosk_id_fkey";
						columns: ["kiosk_id"];
						isOneToOne: false;
						referencedRelation: "kiosks";
						referencedColumns: ["kiosk_id"];
					},
					{
						foreignKeyName: "health_records_measured_by_fkey";
						columns: ["measured_by"];
						isOneToOne: false;
						referencedRelation: "profiles";
						referencedColumns: ["profile_id"];
					}
				];
			};
			recommendations: {
				Row: {
					recommendation_id: string;
					record_id: string;
					template_id: string | null;
					risk_level: RiskLevel;
					recommendation: string;
					created_at: string;
				};
				Insert: {
					recommendation_id?: string;
					record_id: string;
					template_id?: string | null;
					risk_level: RiskLevel;
					recommendation: string;
					created_at?: string;
				};
				Update: Partial<Database["public"]["Tables"]["recommendations"]["Insert"]>;
			
				Relationships: [
					{
						foreignKeyName: "recommendations_record_id_fkey";
						columns: ["record_id"];
						isOneToOne: false;
						referencedRelation: "health_records";
						referencedColumns: ["record_id"];
					},
					{
						foreignKeyName: "recommendations_template_id_fkey";
						columns: ["template_id"];
						isOneToOne: false;
						referencedRelation: "recommendation_templates";
						referencedColumns: ["template_id"];
					}
				];
			};
			recommendation_templates: {
				Row: {
					template_id: string;
					category: string;
					risk_level: RiskLevel;
					title: string;
					recommendation: string;
					created_at: string;
				};
				Insert: {
					template_id?: string;
					category: string;
					risk_level: RiskLevel;
					title: string;
					recommendation: string;
					created_at?: string;
				};
				Update: Partial<Database["public"]["Tables"]["recommendation_templates"]["Insert"]>;
			
				Relationships: [];
			};
			audit_logs: {
				Row: {
					log_id: string;
					profile_id: string | null;
					action: string;
					table_name: string | null;
					record_id: string | null;
					created_at: string;
				};
				Insert: {
					log_id?: string;
					profile_id?: string | null;
					action: string;
					table_name?: string | null;
					record_id?: string | null;
					created_at?: string;
				};
				Update: Partial<Database["public"]["Tables"]["audit_logs"]["Insert"]>;
			
				Relationships: [
					{
						foreignKeyName: "audit_logs_profile_id_fkey";
						columns: ["profile_id"];
						isOneToOne: false;
						referencedRelation: "profiles";
						referencedColumns: ["profile_id"];
					}
				];
			};
		};
	};
}

export type ProfileRow = Database["public"]["Tables"]["profiles"]["Row"];
export type PatientRow = Database["public"]["Tables"]["patients"]["Row"];
export type KioskRow = Database["public"]["Tables"]["kiosks"]["Row"];
export type HealthRecordRow = Database["public"]["Tables"]["health_records"]["Row"];
export type RecommendationRow = Database["public"]["Tables"]["recommendations"]["Row"];
export type RecommendationTemplateRow = Database["public"]["Tables"]["recommendation_templates"]["Row"];
export type AuditLogRow = Database["public"]["Tables"]["audit_logs"]["Row"];
